using AgroTrade.Infrastructure.Data;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroTrade.Infrastructure.Migrations
{
    /// <inheritdoc />
    [Migration("20260930130000_Payments")]
    [Microsoft.EntityFrameworkCore.Infrastructure.DbContext(typeof(AgroTradeDbContext))]
    public partial class Payments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Payments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "OrderId" integer NOT NULL,
                    "Provider" character varying(50) NOT NULL,
                    "Method" character varying(100) NOT NULL,
                    "Status" character varying(50) NOT NULL,
                    "Amount" numeric(18,2) NOT NULL,
                    "Currency" character varying(3) NOT NULL,
                    "ProviderOrderId" character varying(100) NULL,
                    "ProviderOrderPassword" character varying(200) NULL,
                    "ProviderStatus" character varying(100) NULL,
                    "ProviderTransactionCode" character varying(100) NULL,
                    "FailureReason" character varying(500) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    "CompletedAt" timestamp with time zone NULL,
                    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId")
                        REFERENCES "Orders" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Payments_OrderId"
                ON "Payments" ("OrderId");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Payments_ProviderOrderId"
                ON "Payments" ("ProviderOrderId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Payments");
        }
    }
}
