using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AgroTrade.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ProductVisibilityAndActivityLogDetails : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "IsHidden" boolean NOT NULL DEFAULT false;

                CREATE TABLE IF NOT EXISTS "ActivityLogs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "Severity" character varying(40) NOT NULL,
                    "Category" character varying(80) NOT NULL,
                    "Event" character varying(120) NOT NULL,
                    "Message" character varying(500) NOT NULL,
                    "OrderId" integer,
                    "OrderNumber" character varying(80),
                    "Provider" character varying(80),
                    "Status" character varying(80),
                    "Actor" character varying(160),
                    "Details" character varying(4000),
                    CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id")
                );

                ALTER TABLE "ActivityLogs"
                ALTER COLUMN "Details" TYPE character varying(4000);

                CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_CreatedAt" ON "ActivityLogs" ("CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_OrderNumber" ON "ActivityLogs" ("OrderNumber");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Products"
                DROP COLUMN IF EXISTS "IsHidden";

                ALTER TABLE "ActivityLogs"
                ALTER COLUMN "Details" TYPE character varying(1000);
                """);
        }
    }
}
